PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX db: <http://localhost:2020/resource/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX map: <file:/D:/Pumba/WebRoot/d2r-server-0.7/d2r-server-0.7/mapping.n3#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX vocab: <http://localhost:2020/vocab/resource/>
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>
SELECT (count(*) as ?count) ?date
WHERE
{
  ?comments rdf:type vocab:comments .
  ?comments vocab:comments_created_at ?dateTime
}
GROUP BY (fn:substring(str(?dateTime), 1, 10) as ?date)
ORDER BY xsd:date(?date)