PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX vis: <http://code.google.com/apis/visualization/>
PREFIX rep: <http://www.semantic-web.dk/ontologies/semantic-reports/>

SELECT *
{
	?resource	foaf:topic		?report .
	?report		rdf:type		rep:Report .
	?report		rep:visualizedBy	?visualization .
	?visualization	rdf:type		?visType .
        ?visualization  vis:option		?option .
        ?option		rdf:type		?type .
	OPTIONAL
	{
		?option		vis:name	?name .
		?option		vis:value	?value
	}
	#FILTER (?report = <s>)
	FILTER (?resource = <%s>)
}