PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
SELECT DISTINCT * WHERE {
?film dbpedia-owl:gross ?gross .
?film rdfs:label ?name .
?film dbpedia-owl:budget ?budget
FILTER (LANG(?name) = 'en')
}
ORDER BY DESC(xsd:float(?budget))
LIMIT 50