PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT * WHERE {
     ?person <http://dbpedia.org/ontology/networth> ?networth .
     ?person rdfs:label ?name .
     ?person skos:subject <http://dbpedia.org/resource/Category:Living_people>
     FILTER (LANG(?name) = 'en')
     FILTER (DATATYPE(?networth) = <http://dbpedia.org/datatype/usDollar>)
}
ORDER BY DESC(xsd:float(?networth))
LIMIT 50