PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX exp: <http://guardian.dataincubator.org/ns/mp-expenses/>

SELECT * WHERE
{
?mp foaf:name ?name .
?mp exp:total-basic ?total .
?mp exp:salary ?salary .
}
ORDER BY DESC(?total)
LIMIT 50