PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rep: <http://www.semantic-web.dk/ontologies/semantic-reports/>

SELECT *
{
	?endpoint   rdf:type    rep:Endpoint .
        OPTIONAL
        {
            ?endpoint   dc:title  ?title
        }
}
ORDER BY ?title ?endpoint