PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX semrep: <http://www.semantic-web.dk/ontologies/semantic-reports/>

SELECT *
{
	?report	rdf:type	semrep:Report .
	?report	dc:title	?title .
	?report dc:date		?date
}