PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX vis: <http://code.google.com/apis/visualization/>
PREFIX semrep: <http://www.semantic-web.dk/ontologies/semantic-reports/>

SELECT *
{
	?report		rdf:type		semrep:Report .
	?report		semrep:visualizedBy	?visualization .
	# ?visualization	rdf:type		?type
	{
		?visualisation	rdf:type	vis:Table
	}
	UNION
	{
		?visualisation	rdf:type	vis:ScatterChart .
		?visualisation	vis:XBinding	?xBinding .
		?visualisation	vis:YBinding	?yBinding
	}
	UNION
	{
		?visualisation	rdf:type	vis:LineChart .
	}
	UNION
	{
		?visualisation	rdf:type	vis:PieChart .
	}
	UNION
	{
		?visualisation	rdf:type	vis:Map .
	}
	FILTER (?report = <%s>)
}