PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX vis: <http://code.google.com/apis/visualization/>
PREFIX rep: <http://www.semantic-web.dk/ontologies/semantic-reports/>

SELECT *
{
	?report		rdf:type		rep:Report .
	?report		rep:visualizedBy	?visualization .
        ?visualization  vis:binding             ?binding .
        ?binding        rdf:type                ?bindingType .
        ?binding        vis:variableName        ?variable
	FILTER (?report = <%s>)
}