PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  ?company rdf:type <http://cb.semsol.org/ns#Company> .
?company <http://cb.semsol.org/ns#founded_year> ?year .
?company rdfs:label ?label
}
ORDER BY ?year
LIMIT 50