PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX factbook: <http://www4.wiwiss.fu-berlin.de/factbook/ns#>

SELECT DISTINCT *
WHERE
{
?country rdf:type factbook:Country .
?country factbook:countryname_conventionalshortform ?name .
?country factbook:imports ?imports .
?country factbook:exports ?exports
FILTER (?country != <http://www4.wiwiss.fu-berlin.de/factbook/resource/World>)
}
ORDER BY DESC(?exports)