PREFIX movie: <http://data.linkedmdb.org/resource/movie/>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT *
WHERE
{
?film rdf:type movie:film .
?film dc:title ?title .
#?film dc:date ?date .
?film movie:runtime ?runtime
}
ORDER BY DESC(xsd:integer(?runtime))
LIMIT 50