PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT *
WHERE
{
    ?country rdf:type <http://dbpedia.org/ontology/Country> .
    ?country <http://dbpedia.org/property/gdpNominalPerCapita> ?gdp
    FILTER (xsd:double(?gdp) > 0)
}
ORDER BY DESC(xsd:double(?gdp))