PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX census: <http://www.rdfabout.com/rdf/schema/census/>
PREFIX usgovt: <http://www.rdfabout.com/rdf/schema/usgovt/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT *
WHERE
{
?state rdf:type usgovt:State .
?state dc:title ?title .
?state census:population ?population .
?state census:households ?households .
?state geo:lat ?lat .
?state geo:long ?long
}
ORDER BY DESC(?population)
LIMIT 50