PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rep: <http://www.semantic-web.dk/ontologies/semantic-reports/>
PREFIX spin: <http://spinrdf.org/sp#>

SELECT ?endpoint ?title (COUNT(?report) AS ?reportCount)
{
	?endpoint   rdf:type    rep:Endpoint .
        OPTIONAL
        {
            ?endpoint   dc:title  ?title
        }
	?query	spin:from	?endpoint .
	?report	rep:query	?query .
}
GROUP BY ?endpoint
#ORDER BY ?title ?endpoint
ORDER BY DESC(?reportCount) ?title