PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rep: <http://www.semantic-web.dk/ontologies/semantic-reports/>
PREFIX spin: <http://spinrdf.org/sp#>
PREFIX list: <http://jena.hpl.hp.com/ARQ/list#>

SELECT ?predicate
{
	?report	rep:query	?query .
	?query	spin:where	?where .
	?where	list:member	?member .
	?member	spin:predicate	?predicate .
	FILTER (isURI(?predicate))
	FILTER (?report = <%s>)
}